# Site settings
title: "Tecnologías Cuánticas - RAFA 2025"
description: "Evento Satélite especializado en Tecnologías Cuánticas"
baseurl: "/rafa-qs"
url: "https://matibilkis.github.io"

# Event info
event:
  name: "Tecnologías Cuánticas"
  subtitle: "Evento Satélite RAFA 2025"
  dates: "Fechas por confirmar"
  location: "Lugar por definir"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Navigation
header_pages:
  - index.md
  - programa.md
  - ponentes.md
  - inscripcion.md
  - contacto.md

# Language
lang: es