# Site settings
title: "Tecnologías Cuánticas - RAFA 2025"
description: "Evento Satélite especializado en Tecnologías Cuánticas"
baseurl: "/iyq25-rafa"
url: "https://matibilkis.github.io"

# Build settings - GitHub Pages default
markdown: kramdown
highlighter: rouge

# Plugins that GitHub Pages supports
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Navigation pages
header_pages:
  - index.md
  - programa.md

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .bundle
  - .sass-cache
  - .jekyll-cache
  - _site
  - assets/css/main.scss