# Site settings
title: "Tecnologías Cuánticas - RAFA 2025"
description: "Evento Satélite especializado en Tecnologías Cuánticas"
baseurl: "/iyq25-rafa" # MUST match your GitHub repo name exactly
url: "https://matibilkis.github.io"

# Event info
event:
  name: "Tecnologías Cuánticas"
  subtitle: "Evento Satélite RAFA 2025"
  dates: "Fechas por confirmar"
  location: "Lugar por definir"

# Build settings - GitHub Pages compatible
markdown: kramdown
remote_theme: jekyll/minima # Use remote_theme instead of theme for GitHub Pages

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

# Navigation
header_pages:
  - index.md
  - programa.md
  - ponentes.md
  - inscripcion.md
  - contacto.md

# Language
lang: es

# GitHub Pages specific
github: [metadata]